openapi: 3.0.1
info:
  version: '1.0'
  title: Order service
servers:
  - url: '/api/v1/order-service'
tags:
  - name: Order Management
    description: Operations with Order entities
  - name: User Managment
    description: Operations with users
  - name: Dictionary
paths:
  /orders:
    post:
      tags:
        - Order Management
      summary: Create Order
      description: Create order
      operationId: create
      requestBody:
        $ref: '#/components/requestBodies/OrderRequest'
      responses:
        '200':
          description: Created order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDto'
    get:
      tags:
        - Order Management
      summary: Get all orders
      description: Get all orders
      operationId: getAllOrders
      responses:
        '200':
          description: All existing orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderDto'
  /orders/{id}:
    get:
      tags:
        - Order Management
      summary: Get Order
      description: Get Order by id
      operationId: get
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Ok. Order successfully returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullOrderDto'
        '404':
          description: Order not found
    put:
      tags:
        - Order Management
      summary: Update Order
      description: Update Order
      operationId: update
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        $ref: '#/components/requestBodies/OrderRequest'
      responses:
        '200':
          description: Ok. Updated order successfully returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDto'
    delete:
      tags:
        - Order Management
      summary: Delete Order
      description: Delete Order
      operationId: delete
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Ok. Order successfully deleted

  /users/{id}:
    get:
      tags:
        - User Management
      summary: Get User
      description: Get User by id
      operationId: getUserById
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
        '404':
          description: User not found
    put:
      tags:
        - User Management
      summary: Add User
      description: Update User
      operationId: updateUser
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        $ref: '#/components/requestBodies/UserRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
    delete:
      tags:
        - User Management
      summary: Delete User
      description: Delete User
      operationId: deleteUser
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Ok. User successfully deleted

  /users:
    post:
      tags:
        - User Management
      summary: Add User
      description: Add User
      operationId: addUser
      requestBody:
        $ref: '#/components/requestBodies/UserRequest'
      responses:
        '200':
          description: Added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
    get:
      tags:
        - User Management
      summary: Get Users
      description: Get all Users
      operationId: getAllUsers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDto'
  /users/{id}/orders:
    get:
      tags:
        - User Management
      summary: Get User's orders
      description: Return all User's orders
      operationId: getAllUserOrders
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderDto'
components:
  parameters:
    id:
      name: id
      in: path
      description: Order (or User) ID
      required: true
      schema:
        type: string
  requestBodies:
    OrderRequest:
      description: Order request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrderDto'
    UserRequest:
      description: User request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserDto'
  schemas:
    OrderDto:
      type: object
      properties:
        id:
          description: Unique Identifier of Order.
          type: string
          readOnly: true
        name:
          description: Name of Order.
          type: string
          maxLength: 100
        customerId:
          type: string
        total:
          type: number
          format: double
        shippingType:
          $ref: '#/components/schemas/ShippingType'
        status:
          $ref: '#/components/schemas/OrderStatus'
        products:
          type: object
          additionalProperties:
            type: integer
        paymentId:
          type: integer
      required:
        - name
        - customerId
        - total
        - shippingType
        - status
        - products
    UserDto:
      type: object
      properties:
        id:
          description: Unique Identifier of User
          type: string
          readOnly: true
        name:
          description: Name of User.
          type: string
          maxLength: 100
        contact:
          description: Contact of User.
          type: string
          maxLength: 100
        orders:
          description: List of User's orders
          type: array
          items:
            type: string

    ShippingType:
      type: string
      enum:
        - AT_SHOP
        - DELIVERY

    OrderStatus:
      type: string
      enum:
        - IN_PROGRESS
        - DELIVERED
        - PAID
        - COLLECTING

    FullOrderDto:
      OrderDto:
        type: object
        properties:
          id:
            description: Unique Identifier of Order.
            type: string
            readOnly: true
          name:
            description: Name of Order.
            type: string
            maxLength: 100
          customerId:
            type: string
          total:
            type: number
            format: double
          shippingType:
            $ref: '#/components/schemas/ShippingType'
          status:
            $ref: '#/components/schemas/OrderStatus'
          products:
            $ref: '#/components/schemas/ProductDto'
          paymentId:
            type: integer
        required:
          - name
          - customerId
          - total
          - shippingType
          - status
          - products

    ProductDTO:
      type: object
      properties:
        id:
          description: Unique Identifier of Product.
          type: string
          readOnly: true
        type:
          type: string
          readOnly: true
        name:
          description: Name of Product.
          type: string
          readOnly: true
          maxLength: 100
        cost:
          description: Cost of Product.
          type: number
          format: double
          readOnly: true
        amount:
          description: Amount of Product.
          type: integer
          format: int32
          readOnly: true